name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Decode Keystore
      run: |
        echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > release.keystore

    - name: Set up Gradle properties
      run: |
        echo "RELEASE_STORE_FILE=release.keystore" >> local.properties
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> local.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> local.properties
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> local.properties

    - name: Build release
      run: ./gradlew clean assembleRelease lintRelease

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
